In [2]:
print("Hello!")

Hello!


In [3]:
"Data Science"

'Data Science'

In [4]:
2+2

4

# NumPy

In [7]:
# импортирование модуля NumPy
import numpy as np

* создание массивов

In [8]:
# создание 1-мерного массива (вектор-строки) из списка
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [9]:
# создание 2-мерного массива (вектор-столбца) из списка
my_list_2 = [[1],[2],[3],[4],[5]]
my_array_2 = np.array(my_list_2)
my_array_2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
# создание 2-мерного массива (матрицы) из списка
my_list_3 = [[1,2,3,4,5],[6,7,8,9,0]]
my_array_3 = np.array(my_list_3)
my_array_3

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [11]:
# создание массивов из нулей
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# создание вектор-строки со значениями из линейной последовательности
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [18]:
# создание вектор-строки со значениями из равномерного распределения, например в диапазоне от 0 до 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# случайные значения из равномерного распределения в диапазоне от 0 до 1
np.random.random(5)

array([0.020153  , 0.78518086, 0.01888787, 0.30878554, 0.57828564])

In [21]:
np.random.random((5,3))

array([[0.71213789, 0.86592417, 0.33615782],
       [0.33241369, 0.83634281, 0.52139397],
       [0.64571619, 0.69174035, 0.03606099],
       [0.13891124, 0.19779563, 0.98807584],
       [0.0230978 , 0.44890237, 0.18155582]])

In [23]:
# случайные целочисленные значения
np.random.randint(5)

4

In [24]:
np.random.randint(10,20)

15

In [25]:
np.random.randint(1,10,size=5)

array([8, 4, 4, 6, 9])

In [26]:
np.random.randint(1,10,size=(5,5))

array([[6, 8, 3, 8, 4],
       [5, 2, 7, 8, 4],
       [8, 6, 4, 8, 2],
       [4, 9, 2, 8, 2],
       [6, 9, 5, 5, 8]])

- атрибуты

In [28]:
a = np.random.randint(10,size=(3,5))
a

array([[2, 4, 2, 8, 3],
       [9, 3, 3, 1, 4],
       [0, 4, 7, 3, 2]])

In [29]:
# размерность массива (количество измерений/осей)
a.ndim

2

In [30]:
# форма массива
a.shape

(3, 5)

In [31]:
# общее количество значений (элементов)
a.size

15

In [32]:
# тип значений массива
a.dtype

dtype('int32')

In [33]:
np.random.random((5,3)).dtype

dtype('float64')

In [34]:
np.random.random((5,3)).astype("float16")

array([[0.7324  , 0.4553  , 0.0785  ],
       [0.7183  , 0.624   , 0.1353  ],
       [0.0449  , 0.5396  , 0.541   ],
       [0.2566  , 0.918   , 0.002472],
       [0.613   , 0.4844  , 0.566   ]], dtype=float16)

- индексация

In [36]:
a2 = np.random.randint(10,size=10)
a2

array([1, 3, 7, 8, 5, 2, 4, 9, 5, 6])

In [37]:
a2[0]

1

In [38]:
a2[-1]

6

In [39]:
a3 = np.random.randint(10,size=(3,3))
a3

array([[1, 3, 4],
       [0, 2, 8],
       [6, 5, 7]])

In [41]:
# стандартный питоновский синтаксис
a3[2][1]

5

In [ ]:
# принято в numpy