In [2]:
print("Hello!")

Hello!


In [3]:
"Data Science"

'Data Science'

In [4]:
2+2

4

# NumPy

In [6]:
# импортирование модуля NumPy
import numpy as np

* создание массивов

In [9]:
# создание 1-мерного массива (вектор-строки) из списка
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [10]:
# создание 2-мерного массива (вектор-столбца) из списка
my_list_2 = [[1],[2],[3],[4],[5]]
my_array_2 = np.array(my_list_2)
my_array_2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
# создание 2-мерного массива (матрицы) из списка
my_list_3 = [[1,2,3,4,5],[6,7,8,9,0]]
my_array_3 = np.array(my_list_3)
my_array_3

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [11]:
# создание массивов из нулей
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# создание вектор-строки со значениями из линейной последовательности
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [18]:
# создание вектор-строки со значениями из равномерного распределения, например в диапазоне от 0 до 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# случайные значения из равномерного распределения в диапазоне от 0 до 1
np.random.random(5)

array([0.020153  , 0.78518086, 0.01888787, 0.30878554, 0.57828564])

In [21]:
np.random.random((5,3))

array([[0.71213789, 0.86592417, 0.33615782],
       [0.33241369, 0.83634281, 0.52139397],
       [0.64571619, 0.69174035, 0.03606099],
       [0.13891124, 0.19779563, 0.98807584],
       [0.0230978 , 0.44890237, 0.18155582]])

In [23]:
# случайные целочисленные значения
np.random.randint(5)

4

In [24]:
np.random.randint(10,20)

15

In [17]:
np.random.randint(1,10,size=5)

array([2, 1, 4, 2, 9])

In [16]:
np.random.randint(1,10,size=(5,5))

array([[3, 8, 6, 2, 5],
       [5, 5, 5, 5, 1],
       [3, 2, 6, 9, 1],
       [8, 1, 9, 7, 9],
       [5, 5, 1, 3, 9]])

- атрибуты

In [18]:
a = np.random.randint(10,size=(3,5))
a

array([[8, 3, 2, 1, 9],
       [0, 5, 0, 3, 1],
       [9, 7, 4, 8, 4]])

In [29]:
# размерность массива (количество измерений/осей)
a.ndim

2

In [30]:
# форма массива
a.shape

(3, 5)

In [31]:
# общее количество значений (элементов)
a.size

15

In [32]:
# тип значений массива
a.dtype

dtype('int32')

In [33]:
np.random.random((5,3)).dtype

dtype('float64')

In [34]:
np.random.random((5,3)).astype("float16")

array([[0.7324  , 0.4553  , 0.0785  ],
       [0.7183  , 0.624   , 0.1353  ],
       [0.0449  , 0.5396  , 0.541   ],
       [0.2566  , 0.918   , 0.002472],
       [0.613   , 0.4844  , 0.566   ]], dtype=float16)

- индексация

In [4]:
import numpy as np

In [19]:
a2 = np.random.randint(10,size=10)
a2

array([0, 7, 3, 8, 8, 3, 1, 3, 9, 3])

In [20]:
# чтение значений
a2[0]

0

In [38]:
a2[-1]

6

In [21]:
a3 = np.random.randint(10,size=(3,3))
a3

array([[9, 7, 4],
       [9, 2, 5],
       [0, 5, 0]])

In [41]:
# стандартный питоновский синтаксис
a3[2][1]

5

In [22]:
# принято в numpy
a3[2, 1]

5

- срез

In [23]:
# срез по строкам
a3[1:]

array([[9, 2, 5],
       [0, 5, 0]])

In [25]:
# срез по строкам от 1 индекса до конца
# срез по столбцам до 3 не включая
a3[1:, :3]

array([[9, 2, 5],
       [0, 5, 0]])

- Представление (views) и копии (copies)

In [4]:
# список
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [7]:
# срез массива (вектор-строки)
my_arr = np.array(my_list)
my_arr

array([1, 2, 3, 4, 5])

In [28]:
# срез списка
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [29]:
# срез вектор-строки
sub_arr = my_arr[2:]
sub_arr

array([3, 4, 5])

In [30]:
sub_list[0] = 100
my_list

[1, 2, 3, 4, 5]

In [31]:
# массив, созданный срезом другого массива является т.н. представлением
# поэтому, изменения в массиве-представлении отражается на исходный массив
sub_arr[0] = 100
my_arr

array([  1,   2, 100,   4,   5])

In [10]:
# копия массива
copy_arr = my_arr[:2].copy()
copy_arr

array([1, 2])

In [11]:
copy_arr[0] = 10
my_arr

array([1, 2, 3, 4, 5])

In [34]:
copy_arr

array([10,  2])

- Изменение формы

In [12]:
#  1 - мерный массив (вектор-строка)
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr.shape

(9,)

In [14]:
# изменение формы - создание вектор-столбца
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [15]:
# изменение формы -создание матрицы
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Универсальные функции

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([20,30,40,50,60])
print(a)
print(b)

[1 2 3 4 5]
[20 30 40 50 60]


In [18]:
# поэлементное деление
a / b

array([0.05      , 0.06666667, 0.075     , 0.08      , 0.08333333])

In [19]:
# деление на скалярное значение
a/100

array([0.01, 0.02, 0.03, 0.04, 0.05])

In [20]:
100/a


array([100.        ,  50.        ,  33.33333333,  25.        ,
        20.        ])

In [21]:
a>b

array([False, False, False, False, False])

In [22]:
a>5

array([False, False, False, False, False])

- Агрегирование

In [23]:
# агрегирование - вычисление неких сводных показателей
arr_2 = np.random.random(10)
arr_2

array([0.00951213, 0.87563362, 0.93909525, 0.57481937, 0.50784763,
       0.34860153, 0.90132584, 0.34866207, 0.88838191, 0.67947907])

In [24]:
# сумма всех значений
np.sum(arr_2)

6.073358417367288

In [25]:
# минимум показывает
np.min(arr_2)

0.009512126777120211

In [26]:
# среднее арифметическое
np.mean(arr_2)

0.6073358417367288

In [27]:
np.max(arr_2)

0.9390952511261863

- Маскирование

In [30]:
# извлечение значений. которые отвечают некоторому условию
x = np.random.randint(10, size=7)
x

array([0, 0, 8, 9, 6, 4, 1])

In [31]:
x<5

array([ True,  True, False, False, False,  True,  True])

In [32]:
# новый массив только с этими условиями
x[x<5]

array([0, 0, 4, 1])

In [39]:
# тем значениям которые меньше 5 присвоить 111
x[x<5] = 111
x

array([111, 111,   8,   9,   6, 111, 111])

- "Прихотливая" индексация

In [40]:
# "Прихотливая" индексация - выбор значений по определенным индексам
x = np.random.randint(10, size=7)
x

array([5, 5, 1, 0, 5, 7, 4])

In [41]:
# выбор значений по списку с индексами
x[[5,0,3]]

array([7, 5, 0])

In [42]:
# выбор значений по массиву с индексами, который находится в переменной indices
indices = np.array([5,0,3])
x[indices]

array([7, 5, 0])

In [44]:
x2 = np.random.randint(10, size=(3,5))
x2

array([[5, 8, 6, 3, 2],
       [4, 4, 3, 6, 2],
       [0, 7, 4, 2, 6]])

In [50]:
# сочетание среза и прихотливой индексации
x2[1:, [2,0]]

array([[6, 5],
       [3, 4],
       [4, 0]])

In [51]:
x2<5

array([[False, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True,  True, False]])

In [57]:
# сочетание маскирования и прихотливой индексации
x2[x2>5][[1,0,3]]

array([6, 8, 7])